//
//  ListContactCleanPresenter.swift
//  ListContact
//
//  Created by Álvaro Fernandes on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListContactCleanPresentationLogic {
    func startLoading()
    func stopLoading()
    func loadList(_ listContact: [Contact])
    func showError()
}

class ListContactCleanPresenter: ListContactCleanPresentationLogic {
    
    weak var viewController: ListContactCleanDisplayLogic?
    
    func loadList(_ listContact: [Contact]) {
        let viewModel: ListContactCleanViewModel = ListContactCleanViewModel(listContact)
        viewController?.loadList(viewModel: viewModel)
    }
    
    func showError() {
        viewController?.showError()
    }
    
    func startLoading() {
        viewController?.startLoading()
    }
    
    func stopLoading() {
        viewController?.stopLoading()
    }
  
}
