//
//  ListContactCleanRouter.swift
//  ListContact
//
//  Created by Álvaro Fernandes on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListContactCleanRoutingLogic {
  
}

protocol ListContactCleanDataPassing {
  var dataStore: ListContactCleanDataStore? { get }
}

class ListContactCleanRouter: NSObject, ListContactCleanRoutingLogic, ListContactCleanDataPassing {
    
    weak var viewController: ListContactCleanViewController?
    var dataStore: ListContactCleanDataStore?
  
//    func routeToAny(){
//        guard let destinationVC = NextViewController() else { return }
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
//    }
//
//    func passDataToSomewhere(source: ListContactCleanDataStore, destination: inout NextDataStore) {
//      destination.session = source.session
//    }
}
