//
//  ListContactCleanInteractor.swift
//  ListContact
//
//  Created by Álvaro Fernandes on 23/03/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListContactCleanBusinessLogic {
  func load()
}

protocol ListContactCleanDataStore {
  //var name: String { get set }
}

class ListContactCleanInteractor: ListContactCleanBusinessLogic, ListContactCleanDataStore {
    
    var presenter: ListContactCleanPresentationLogic?
    var worker: ListContactCleanWorker?
    
    init(worker: ListContactCleanWorker = ListContactCleanWorker()) {
      self.worker = worker
    }
    
    func load() {
        presenter?.startLoading()
        worker?.getData().done(handleSuccess).catch(handleFailure)
    }
    
    func handleSuccess(_ response: [Contact]) {
        presenter?.loadList(response)
        presenter?.stopLoading()
    }
    
    func handleFailure(_ error: Error) {
        presenter?.showError()
    }

    
}
